
import os

top = '.'
out = 'build'


ns3_lib_name = "ns3-dev-%s-%s"
""" The name of a ns3 shared library """

def options(opt):
        opt.load('compiler_cxx')
        
        opt.add_option('--run',
                   help=('Run a locally built program; argument can be a program name,'
                         ' or a command starting with the program name.'),
                   type="string", default='', dest='run')

	opt.add_option('--ns3-path',
                       help='Install path to ns3',
                       action="store", type="string", default=None,
                       dest='ns3_path')

	opt.add_option('--ns3-type',
                       help='The build type used when building ns3 [debug|release]',
                       action="store", type="string", default='debug',
                       dest='ns3_type')

def configure(conf):
        
	if not conf.options.ns3_path:
            conf.fatal('Please specify a path to ns3')

	ns3_path = os.path.abspath(os.path.expanduser(conf.options.ns3_path))
	
	if not os.path.isdir(ns3_path): 
        	conf.fatal('The specified ns3 path "%s" is not a valid directory' % ns3_path)

	ns3_build = os.path.join(ns3_path, 'build')
        if not os.path.isdir(ns3_build): 
		conf.fatal('Could not find the ns3 build directory in "%s"' % ns3_build)

	ns3_type = conf.options.ns3_type
	
	if not ns3_type:
		conf.fatal('You must specify the build type')

        conf.load('compiler_cxx')       
        conf.env['NS3_BUILD'] = [ns3_build]      
 	
	conf.env['NS3_TYPE'] = ns3_type

def build(bld):

    ns3_build = bld.env['NS3_BUILD'] 
    ns3_type = bld.env['NS3_TYPE'] 
    
    ns3_lib_dir = bld.root.find_dir(ns3_build)
    ns3_libs = ns3_lib_dir.ant_glob('*.so')
    
     
    ns3_libs = [str(lib).split('/')[-1] for lib in ns3_libs]
    ns3_libs = [lib[3:] for lib in ns3_libs]
    ns3_libs = [lib[:-3] for lib in ns3_libs]
    

    
    bld.env['INCLUDES'] += ['/home/peyman/kodo/','/home/peyman/kodo/examples/encode_decode_simple/bundle_dependencies/fifi/', '/home/peyman/kodo/kodo/rlnc/','/home/peyman/kodo/examples/encode_decode_simple/bundle_dependencies/boost/boost/','/home/peyman/kodo/examples/encode_decode_simple/bundle_dependencies/sak/','/home/peyman/peyman/ns3-networkcoding/adhoc_simulations/', '/home/peyman/peyman/ns3-networkcoding/adhoc_simulations/repos/ns-3-allinone/ns-3-dev/build/']
  
    bld.program(source = ['adhoc.cc', 'pep-wifi-net-device.cc', 'code-header.cc'],
                target = 'adhoc',
                libpath = bld.env['INCLUDES'],
                lib = ns3_libs, 
                cxxflags = '-g',
                features = 'cxx cxxprogram')
                
                


